### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by chiefjazzdiewltr** [chiefjazzdiewltr/MoviesFolder#1]
### Things I already plan on doing
- [x] Fix the weird visual updating thing with the listbox rows
- [x] Tidy up the GUI and fine tune some of the little nit picks
- [x] Add a visual key for the listbox
### Long term goals
- [ ] Add a sorting system to the list box
- [ ] Add either a custom inbuilt media player, or open a existing one
- [ ] Possibly switch file export to xlsx from csv (or support both)
